/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 f35.glb --transform 
Files: f35.glb [2.97MB] > /Users/delek/Dev/3d-model-scroll-explr/public/models/f35-transformed.glb [399.36KB] (87%)
*/

import { useGLTF } from '@react-three/drei'

export function F35(props) {
  const { nodes, materials } = useGLTF('/models/f35-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['F-35-airframe']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.glass} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['inst-glass']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['F-35-landingLights']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/f35-transformed.glb')
